// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkID) Reset() {
	*x = ChunkID{}
	mi := &file_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkID) ProtoMessage() {}

func (x *ChunkID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkID.ProtoReflect.Descriptor instead.
func (*ChunkID) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkID) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ChunkID) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Reveal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkID               `protobuf:"bytes,1,opt,name=chunkId,proto3" json:"chunkId,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	PlayerId      int32                  `protobuf:"varint,4,opt,name=playerId,proto3" json:"playerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reveal) Reset() {
	*x = Reveal{}
	mi := &file_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reveal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reveal) ProtoMessage() {}

func (x *Reveal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reveal.ProtoReflect.Descriptor instead.
func (*Reveal) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Reveal) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *Reveal) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Reveal) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Reveal) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type Flag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkID               `protobuf:"bytes,1,opt,name=chunkId,proto3" json:"chunkId,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	PlayerId      int32                  `protobuf:"varint,4,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag) Reset() {
	*x = Flag{}
	mi := &file_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Flag) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *Flag) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Flag) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Flag) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Flag) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Hello) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hello) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	ViewX         int32                  `protobuf:"varint,4,opt,name=viewX,proto3" json:"viewX,omitempty"`
	ViewY         int32                  `protobuf:"varint,5,opt,name=viewY,proto3" json:"viewY,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_proto_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Welcome) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Welcome) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Welcome) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Welcome) GetViewX() int32 {
	if x != nil {
		return x.ViewX
	}
	return 0
}

func (x *Welcome) GetViewY() int32 {
	if x != nil {
		return x.ViewY
	}
	return 0
}

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkX        int32                  `protobuf:"varint,1,opt,name=chunkX,proto3" json:"chunkX,omitempty"`
	ChunkY        int32                  `protobuf:"varint,2,opt,name=chunkY,proto3" json:"chunkY,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_proto_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Subscribe) GetChunkX() int32 {
	if x != nil {
		return x.ChunkX
	}
	return 0
}

func (x *Subscribe) GetChunkY() int32 {
	if x != nil {
		return x.ChunkY
	}
	return 0
}

type Unsubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkX        int32                  `protobuf:"varint,1,opt,name=chunkX,proto3" json:"chunkX,omitempty"`
	ChunkY        int32                  `protobuf:"varint,2,opt,name=chunkY,proto3" json:"chunkY,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unsubscribe) Reset() {
	*x = Unsubscribe{}
	mi := &file_proto_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsubscribe) ProtoMessage() {}

func (x *Unsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsubscribe.ProtoReflect.Descriptor instead.
func (*Unsubscribe) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{6}
}

func (x *Unsubscribe) GetChunkX() int32 {
	if x != nil {
		return x.ChunkX
	}
	return 0
}

func (x *Unsubscribe) GetChunkY() int32 {
	if x != nil {
		return x.ChunkY
	}
	return 0
}

type FlagLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagLocation) Reset() {
	*x = FlagLocation{}
	mi := &file_proto_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagLocation) ProtoMessage() {}

func (x *FlagLocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagLocation.ProtoReflect.Descriptor instead.
func (*FlagLocation) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{7}
}

func (x *FlagLocation) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FlagLocation) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type FlagGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         string                 `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	PlayerId      int32                  `protobuf:"varint,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Locations     []*FlagLocation        `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagGroup) Reset() {
	*x = FlagGroup{}
	mi := &file_proto_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagGroup) ProtoMessage() {}

func (x *FlagGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagGroup.ProtoReflect.Descriptor instead.
func (*FlagGroup) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{8}
}

func (x *FlagGroup) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *FlagGroup) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *FlagGroup) GetLocations() []*FlagLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

type ChunkSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkID               `protobuf:"bytes,1,opt,name=chunkId,proto3" json:"chunkId,omitempty"`
	Seed          []byte                 `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`       // 8‑byte little‑endian HMAC seed (exact 64 bits, JS‑safe).
	Reveals       []byte                 `protobuf:"bytes,3,opt,name=reveals,proto3" json:"reveals,omitempty"` // RLE compressed reveal bitset
	FlagGroups    []*FlagGroup           `protobuf:"bytes,4,rep,name=flagGroups,proto3" json:"flagGroups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkSync) Reset() {
	*x = ChunkSync{}
	mi := &file_proto_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkSync) ProtoMessage() {}

func (x *ChunkSync) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkSync.ProtoReflect.Descriptor instead.
func (*ChunkSync) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ChunkSync) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *ChunkSync) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *ChunkSync) GetReveals() []byte {
	if x != nil {
		return x.Reveals
	}
	return nil
}

func (x *ChunkSync) GetFlagGroups() []*FlagGroup {
	if x != nil {
		return x.FlagGroups
	}
	return nil
}

type RevealAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealAck) Reset() {
	*x = RevealAck{}
	mi := &file_proto_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealAck) ProtoMessage() {}

func (x *RevealAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealAck.ProtoReflect.Descriptor instead.
func (*RevealAck) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{10}
}

func (x *RevealAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type FlagAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagAck) Reset() {
	*x = FlagAck{}
	mi := &file_proto_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagAck) ProtoMessage() {}

func (x *FlagAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagAck.ProtoReflect.Descriptor instead.
func (*FlagAck) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{11}
}

func (x *FlagAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Score         string                 `protobuf:"bytes,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_proto_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{12}
}

func (x *LeaderboardEntry) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *LeaderboardEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeaderboardEntry) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

type Leaderboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leaderboard) Reset() {
	*x = Leaderboard{}
	mi := &file_proto_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leaderboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leaderboard) ProtoMessage() {}

func (x *Leaderboard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leaderboard.ProtoReflect.Descriptor instead.
func (*Leaderboard) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{13}
}

func (x *Leaderboard) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Leaderboard) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ScoreUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	WorldX        int32                  `protobuf:"varint,2,opt,name=worldX,proto3" json:"worldX,omitempty"` // world X coordinate where the score change occurred
	WorldY        int32                  `protobuf:"varint,3,opt,name=worldY,proto3" json:"worldY,omitempty"` // world Y coordinate where the score change occurred
	Delta         int32                  `protobuf:"varint,4,opt,name=delta,proto3" json:"delta,omitempty"`   // score change amount (positive or negative)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreUpdate) Reset() {
	*x = ScoreUpdate{}
	mi := &file_proto_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreUpdate) ProtoMessage() {}

func (x *ScoreUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreUpdate.ProtoReflect.Descriptor instead.
func (*ScoreUpdate) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{14}
}

func (x *ScoreUpdate) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoreUpdate) GetWorldX() int32 {
	if x != nil {
		return x.WorldX
	}
	return 0
}

func (x *ScoreUpdate) GetWorldY() int32 {
	if x != nil {
		return x.WorldY
	}
	return 0
}

func (x *ScoreUpdate) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type ViewUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewX         int32                  `protobuf:"varint,1,opt,name=viewX,proto3" json:"viewX,omitempty"`
	ViewY         int32                  `protobuf:"varint,2,opt,name=viewY,proto3" json:"viewY,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewUpdate) Reset() {
	*x = ViewUpdate{}
	mi := &file_proto_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewUpdate) ProtoMessage() {}

func (x *ViewUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewUpdate.ProtoReflect.Descriptor instead.
func (*ViewUpdate) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{15}
}

func (x *ViewUpdate) GetViewX() int32 {
	if x != nil {
		return x.ViewX
	}
	return 0
}

func (x *ViewUpdate) GetViewY() int32 {
	if x != nil {
		return x.ViewY
	}
	return 0
}

type Msg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Msg_Hello
	//	*Msg_Welcome
	//	*Msg_Reveal
	//	*Msg_Flag
	//	*Msg_Subscribe
	//	*Msg_Unsubscribe
	//	*Msg_ChunkSync
	//	*Msg_RevealAck
	//	*Msg_FlagAck
	//	*Msg_Leaderboard
	//	*Msg_ScoreUpdate
	//	*Msg_ViewUpdate
	Payload       isMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_proto_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{16}
}

func (x *Msg) GetPayload() isMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Msg) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*Msg_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Msg) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Payload.(*Msg_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *Msg) GetReveal() *Reveal {
	if x != nil {
		if x, ok := x.Payload.(*Msg_Reveal); ok {
			return x.Reveal
		}
	}
	return nil
}

func (x *Msg) GetFlag() *Flag {
	if x != nil {
		if x, ok := x.Payload.(*Msg_Flag); ok {
			return x.Flag
		}
	}
	return nil
}

func (x *Msg) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Payload.(*Msg_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *Msg) GetUnsubscribe() *Unsubscribe {
	if x != nil {
		if x, ok := x.Payload.(*Msg_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *Msg) GetChunkSync() *ChunkSync {
	if x != nil {
		if x, ok := x.Payload.(*Msg_ChunkSync); ok {
			return x.ChunkSync
		}
	}
	return nil
}

func (x *Msg) GetRevealAck() *RevealAck {
	if x != nil {
		if x, ok := x.Payload.(*Msg_RevealAck); ok {
			return x.RevealAck
		}
	}
	return nil
}

func (x *Msg) GetFlagAck() *FlagAck {
	if x != nil {
		if x, ok := x.Payload.(*Msg_FlagAck); ok {
			return x.FlagAck
		}
	}
	return nil
}

func (x *Msg) GetLeaderboard() *Leaderboard {
	if x != nil {
		if x, ok := x.Payload.(*Msg_Leaderboard); ok {
			return x.Leaderboard
		}
	}
	return nil
}

func (x *Msg) GetScoreUpdate() *ScoreUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Msg_ScoreUpdate); ok {
			return x.ScoreUpdate
		}
	}
	return nil
}

func (x *Msg) GetViewUpdate() *ViewUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Msg_ViewUpdate); ok {
			return x.ViewUpdate
		}
	}
	return nil
}

type isMsg_Payload interface {
	isMsg_Payload()
}

type Msg_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type Msg_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,2,opt,name=welcome,proto3,oneof"`
}

type Msg_Reveal struct {
	Reveal *Reveal `protobuf:"bytes,3,opt,name=reveal,proto3,oneof"`
}

type Msg_Flag struct {
	Flag *Flag `protobuf:"bytes,4,opt,name=flag,proto3,oneof"`
}

type Msg_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,5,opt,name=subscribe,proto3,oneof"`
}

type Msg_Unsubscribe struct {
	Unsubscribe *Unsubscribe `protobuf:"bytes,6,opt,name=unsubscribe,proto3,oneof"`
}

type Msg_ChunkSync struct {
	ChunkSync *ChunkSync `protobuf:"bytes,7,opt,name=chunkSync,proto3,oneof"`
}

type Msg_RevealAck struct {
	RevealAck *RevealAck `protobuf:"bytes,8,opt,name=revealAck,proto3,oneof"`
}

type Msg_FlagAck struct {
	FlagAck *FlagAck `protobuf:"bytes,9,opt,name=flagAck,proto3,oneof"`
}

type Msg_Leaderboard struct {
	Leaderboard *Leaderboard `protobuf:"bytes,10,opt,name=leaderboard,proto3,oneof"`
}

type Msg_ScoreUpdate struct {
	ScoreUpdate *ScoreUpdate `protobuf:"bytes,11,opt,name=scoreUpdate,proto3,oneof"`
}

type Msg_ViewUpdate struct {
	ViewUpdate *ViewUpdate `protobuf:"bytes,12,opt,name=viewUpdate,proto3,oneof"`
}

func (*Msg_Hello) isMsg_Payload() {}

func (*Msg_Welcome) isMsg_Payload() {}

func (*Msg_Reveal) isMsg_Payload() {}

func (*Msg_Flag) isMsg_Payload() {}

func (*Msg_Subscribe) isMsg_Payload() {}

func (*Msg_Unsubscribe) isMsg_Payload() {}

func (*Msg_ChunkSync) isMsg_Payload() {}

func (*Msg_RevealAck) isMsg_Payload() {}

func (*Msg_FlagAck) isMsg_Payload() {}

func (*Msg_Leaderboard) isMsg_Payload() {}

func (*Msg_ScoreUpdate) isMsg_Payload() {}

func (*Msg_ViewUpdate) isMsg_Payload() {}

var File_proto_messages_proto protoreflect.FileDescriptor

const file_proto_messages_proto_rawDesc = "" +
	"\n" +
	"\x14proto/messages.proto\x12\x02ms\"%\n" +
	"\aChunkID\x12\f\n" +
	"\x01X\x18\x01 \x01(\x05R\x01X\x12\f\n" +
	"\x01Y\x18\x02 \x01(\x05R\x01Y\"g\n" +
	"\x06Reveal\x12%\n" +
	"\achunkId\x18\x01 \x01(\v2\v.ms.ChunkIDR\achunkId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x1a\n" +
	"\bplayerId\x18\x04 \x01(\x05R\bplayerId\"{\n" +
	"\x04Flag\x12%\n" +
	"\achunkId\x18\x01 \x01(\v2\v.ms.ChunkIDR\achunkId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x1a\n" +
	"\bplayerId\x18\x04 \x01(\x05R\bplayerId\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\"M\n" +
	"\x05Hello\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x05R\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\"{\n" +
	"\aWelcome\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x05R\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x14\n" +
	"\x05viewX\x18\x04 \x01(\x05R\x05viewX\x12\x14\n" +
	"\x05viewY\x18\x05 \x01(\x05R\x05viewY\";\n" +
	"\tSubscribe\x12\x16\n" +
	"\x06chunkX\x18\x01 \x01(\x05R\x06chunkX\x12\x16\n" +
	"\x06chunkY\x18\x02 \x01(\x05R\x06chunkY\"=\n" +
	"\vUnsubscribe\x12\x16\n" +
	"\x06chunkX\x18\x01 \x01(\x05R\x06chunkX\x12\x16\n" +
	"\x06chunkY\x18\x02 \x01(\x05R\x06chunkY\"*\n" +
	"\fFlagLocation\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"m\n" +
	"\tFlagGroup\x12\x14\n" +
	"\x05color\x18\x01 \x01(\tR\x05color\x12\x1a\n" +
	"\bplayerId\x18\x02 \x01(\x05R\bplayerId\x12.\n" +
	"\tlocations\x18\x03 \x03(\v2\x10.ms.FlagLocationR\tlocations\"\x8f\x01\n" +
	"\tChunkSync\x12%\n" +
	"\achunkId\x18\x01 \x01(\v2\v.ms.ChunkIDR\achunkId\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\fR\x04seed\x12\x18\n" +
	"\areveals\x18\x03 \x01(\fR\areveals\x12-\n" +
	"\n" +
	"flagGroups\x18\x04 \x03(\v2\r.ms.FlagGroupR\n" +
	"flagGroups\"\x1b\n" +
	"\tRevealAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x19\n" +
	"\aFlagAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"X\n" +
	"\x10LeaderboardEntry\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\x05R\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x03 \x01(\tR\x05score\"W\n" +
	"\vLeaderboard\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12.\n" +
	"\aentries\x18\x02 \x03(\v2\x14.ms.LeaderboardEntryR\aentries\"i\n" +
	"\vScoreUpdate\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\x12\x16\n" +
	"\x06worldX\x18\x02 \x01(\x05R\x06worldX\x12\x16\n" +
	"\x06worldY\x18\x03 \x01(\x05R\x06worldY\x12\x14\n" +
	"\x05delta\x18\x04 \x01(\x05R\x05delta\"8\n" +
	"\n" +
	"ViewUpdate\x12\x14\n" +
	"\x05viewX\x18\x01 \x01(\x05R\x05viewX\x12\x14\n" +
	"\x05viewY\x18\x02 \x01(\x05R\x05viewY\"\xa9\x04\n" +
	"\x03Msg\x12!\n" +
	"\x05hello\x18\x01 \x01(\v2\t.ms.HelloH\x00R\x05hello\x12'\n" +
	"\awelcome\x18\x02 \x01(\v2\v.ms.WelcomeH\x00R\awelcome\x12$\n" +
	"\x06reveal\x18\x03 \x01(\v2\n" +
	".ms.RevealH\x00R\x06reveal\x12\x1e\n" +
	"\x04flag\x18\x04 \x01(\v2\b.ms.FlagH\x00R\x04flag\x12-\n" +
	"\tsubscribe\x18\x05 \x01(\v2\r.ms.SubscribeH\x00R\tsubscribe\x123\n" +
	"\vunsubscribe\x18\x06 \x01(\v2\x0f.ms.UnsubscribeH\x00R\vunsubscribe\x12-\n" +
	"\tchunkSync\x18\a \x01(\v2\r.ms.ChunkSyncH\x00R\tchunkSync\x12-\n" +
	"\trevealAck\x18\b \x01(\v2\r.ms.RevealAckH\x00R\trevealAck\x12'\n" +
	"\aflagAck\x18\t \x01(\v2\v.ms.FlagAckH\x00R\aflagAck\x123\n" +
	"\vleaderboard\x18\n" +
	" \x01(\v2\x0f.ms.LeaderboardH\x00R\vleaderboard\x123\n" +
	"\vscoreUpdate\x18\v \x01(\v2\x0f.ms.ScoreUpdateH\x00R\vscoreUpdate\x120\n" +
	"\n" +
	"viewUpdate\x18\f \x01(\v2\x0e.ms.ViewUpdateH\x00R\n" +
	"viewUpdateB\t\n" +
	"\apayloadB\x1cZ\x1ainfinite-minesweeper/protob\x06proto3"

var (
	file_proto_messages_proto_rawDescOnce sync.Once
	file_proto_messages_proto_rawDescData []byte
)

func file_proto_messages_proto_rawDescGZIP() []byte {
	file_proto_messages_proto_rawDescOnce.Do(func() {
		file_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)))
	})
	return file_proto_messages_proto_rawDescData
}

var file_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_messages_proto_goTypes = []any{
	(*ChunkID)(nil),          // 0: ms.ChunkID
	(*Reveal)(nil),           // 1: ms.Reveal
	(*Flag)(nil),             // 2: ms.Flag
	(*Hello)(nil),            // 3: ms.Hello
	(*Welcome)(nil),          // 4: ms.Welcome
	(*Subscribe)(nil),        // 5: ms.Subscribe
	(*Unsubscribe)(nil),      // 6: ms.Unsubscribe
	(*FlagLocation)(nil),     // 7: ms.FlagLocation
	(*FlagGroup)(nil),        // 8: ms.FlagGroup
	(*ChunkSync)(nil),        // 9: ms.ChunkSync
	(*RevealAck)(nil),        // 10: ms.RevealAck
	(*FlagAck)(nil),          // 11: ms.FlagAck
	(*LeaderboardEntry)(nil), // 12: ms.LeaderboardEntry
	(*Leaderboard)(nil),      // 13: ms.Leaderboard
	(*ScoreUpdate)(nil),      // 14: ms.ScoreUpdate
	(*ViewUpdate)(nil),       // 15: ms.ViewUpdate
	(*Msg)(nil),              // 16: ms.Msg
}
var file_proto_messages_proto_depIdxs = []int32{
	0,  // 0: ms.Reveal.chunkId:type_name -> ms.ChunkID
	0,  // 1: ms.Flag.chunkId:type_name -> ms.ChunkID
	7,  // 2: ms.FlagGroup.locations:type_name -> ms.FlagLocation
	0,  // 3: ms.ChunkSync.chunkId:type_name -> ms.ChunkID
	8,  // 4: ms.ChunkSync.flagGroups:type_name -> ms.FlagGroup
	12, // 5: ms.Leaderboard.entries:type_name -> ms.LeaderboardEntry
	3,  // 6: ms.Msg.hello:type_name -> ms.Hello
	4,  // 7: ms.Msg.welcome:type_name -> ms.Welcome
	1,  // 8: ms.Msg.reveal:type_name -> ms.Reveal
	2,  // 9: ms.Msg.flag:type_name -> ms.Flag
	5,  // 10: ms.Msg.subscribe:type_name -> ms.Subscribe
	6,  // 11: ms.Msg.unsubscribe:type_name -> ms.Unsubscribe
	9,  // 12: ms.Msg.chunkSync:type_name -> ms.ChunkSync
	10, // 13: ms.Msg.revealAck:type_name -> ms.RevealAck
	11, // 14: ms.Msg.flagAck:type_name -> ms.FlagAck
	13, // 15: ms.Msg.leaderboard:type_name -> ms.Leaderboard
	14, // 16: ms.Msg.scoreUpdate:type_name -> ms.ScoreUpdate
	15, // 17: ms.Msg.viewUpdate:type_name -> ms.ViewUpdate
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_messages_proto_init() }
func file_proto_messages_proto_init() {
	if File_proto_messages_proto != nil {
		return
	}
	file_proto_messages_proto_msgTypes[16].OneofWrappers = []any{
		(*Msg_Hello)(nil),
		(*Msg_Welcome)(nil),
		(*Msg_Reveal)(nil),
		(*Msg_Flag)(nil),
		(*Msg_Subscribe)(nil),
		(*Msg_Unsubscribe)(nil),
		(*Msg_ChunkSync)(nil),
		(*Msg_RevealAck)(nil),
		(*Msg_FlagAck)(nil),
		(*Msg_Leaderboard)(nil),
		(*Msg_ScoreUpdate)(nil),
		(*Msg_ViewUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_messages_proto_goTypes,
		DependencyIndexes: file_proto_messages_proto_depIdxs,
		MessageInfos:      file_proto_messages_proto_msgTypes,
	}.Build()
	File_proto_messages_proto = out.File
	file_proto_messages_proto_goTypes = nil
	file_proto_messages_proto_depIdxs = nil
}
