// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Hello) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hello) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Welcome) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Welcome) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Welcome) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type RevealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkX        int32                  `protobuf:"varint,1,opt,name=chunk_x,json=chunkX,proto3" json:"chunk_x,omitempty"`
	ChunkY        int32                  `protobuf:"varint,2,opt,name=chunk_y,json=chunkY,proto3" json:"chunk_y,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealRequest) Reset() {
	*x = RevealRequest{}
	mi := &file_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealRequest) ProtoMessage() {}

func (x *RevealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealRequest.ProtoReflect.Descriptor instead.
func (*RevealRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *RevealRequest) GetChunkX() int32 {
	if x != nil {
		return x.ChunkX
	}
	return 0
}

func (x *RevealRequest) GetChunkY() int32 {
	if x != nil {
		return x.ChunkY
	}
	return 0
}

func (x *RevealRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RevealRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type RevealAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealAck) Reset() {
	*x = RevealAck{}
	mi := &file_proto_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealAck) ProtoMessage() {}

func (x *RevealAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealAck.ProtoReflect.Descriptor instead.
func (*RevealAck) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{3}
}

func (x *RevealAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type FlagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkX        int32                  `protobuf:"varint,1,opt,name=chunk_x,json=chunkX,proto3" json:"chunk_x,omitempty"`
	ChunkY        int32                  `protobuf:"varint,2,opt,name=chunk_y,json=chunkY,proto3" json:"chunk_y,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagRequest) Reset() {
	*x = FlagRequest{}
	mi := &file_proto_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagRequest) ProtoMessage() {}

func (x *FlagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagRequest.ProtoReflect.Descriptor instead.
func (*FlagRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *FlagRequest) GetChunkX() int32 {
	if x != nil {
		return x.ChunkX
	}
	return 0
}

func (x *FlagRequest) GetChunkY() int32 {
	if x != nil {
		return x.ChunkY
	}
	return 0
}

func (x *FlagRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FlagRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type FlagAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagAck) Reset() {
	*x = FlagAck{}
	mi := &file_proto_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagAck) ProtoMessage() {}

func (x *FlagAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagAck.ProtoReflect.Descriptor instead.
func (*FlagAck) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{5}
}

func (x *FlagAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkX        int32                  `protobuf:"varint,1,opt,name=chunk_x,json=chunkX,proto3" json:"chunk_x,omitempty"`
	ChunkY        int32                  `protobuf:"varint,2,opt,name=chunk_y,json=chunkY,proto3" json:"chunk_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_proto_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{6}
}

func (x *Subscribe) GetChunkX() int32 {
	if x != nil {
		return x.ChunkX
	}
	return 0
}

func (x *Subscribe) GetChunkY() int32 {
	if x != nil {
		return x.ChunkY
	}
	return 0
}

type Unsubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkX        int32                  `protobuf:"varint,1,opt,name=chunk_x,json=chunkX,proto3" json:"chunk_x,omitempty"`
	ChunkY        int32                  `protobuf:"varint,2,opt,name=chunk_y,json=chunkY,proto3" json:"chunk_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unsubscribe) Reset() {
	*x = Unsubscribe{}
	mi := &file_proto_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsubscribe) ProtoMessage() {}

func (x *Unsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsubscribe.ProtoReflect.Descriptor instead.
func (*Unsubscribe) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{7}
}

func (x *Unsubscribe) GetChunkX() int32 {
	if x != nil {
		return x.ChunkX
	}
	return 0
}

func (x *Unsubscribe) GetChunkY() int32 {
	if x != nil {
		return x.ChunkY
	}
	return 0
}

type RevealEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkX        int32                  `protobuf:"varint,1,opt,name=chunk_x,json=chunkX,proto3" json:"chunk_x,omitempty"`
	ChunkY        int32                  `protobuf:"varint,2,opt,name=chunk_y,json=chunkY,proto3" json:"chunk_y,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	PlayerId      int32                  `protobuf:"varint,5,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealEvent) Reset() {
	*x = RevealEvent{}
	mi := &file_proto_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealEvent) ProtoMessage() {}

func (x *RevealEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealEvent.ProtoReflect.Descriptor instead.
func (*RevealEvent) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{8}
}

func (x *RevealEvent) GetChunkX() int32 {
	if x != nil {
		return x.ChunkX
	}
	return 0
}

func (x *RevealEvent) GetChunkY() int32 {
	if x != nil {
		return x.ChunkY
	}
	return 0
}

func (x *RevealEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RevealEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *RevealEvent) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type FlagEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkX        int32                  `protobuf:"varint,1,opt,name=chunk_x,json=chunkX,proto3" json:"chunk_x,omitempty"`
	ChunkY        int32                  `protobuf:"varint,2,opt,name=chunk_y,json=chunkY,proto3" json:"chunk_y,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	PlayerId      int32                  `protobuf:"varint,5,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagEvent) Reset() {
	*x = FlagEvent{}
	mi := &file_proto_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagEvent) ProtoMessage() {}

func (x *FlagEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagEvent.ProtoReflect.Descriptor instead.
func (*FlagEvent) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{9}
}

func (x *FlagEvent) GetChunkX() int32 {
	if x != nil {
		return x.ChunkX
	}
	return 0
}

func (x *FlagEvent) GetChunkY() int32 {
	if x != nil {
		return x.ChunkY
	}
	return 0
}

func (x *FlagEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FlagEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *FlagEvent) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *FlagEvent) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type ChunkSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkX        int32                  `protobuf:"varint,1,opt,name=chunk_x,json=chunkX,proto3" json:"chunk_x,omitempty"`
	ChunkY        int32                  `protobuf:"varint,2,opt,name=chunk_y,json=chunkY,proto3" json:"chunk_y,omitempty"`
	Seed          uint64                 `protobuf:"varint,3,opt,name=seed,proto3" json:"seed,omitempty"`
	Reveals       []*RevealEvent         `protobuf:"bytes,4,rep,name=reveals,proto3" json:"reveals,omitempty"`
	Flags         []*FlagEvent           `protobuf:"bytes,5,rep,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkSync) Reset() {
	*x = ChunkSync{}
	mi := &file_proto_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkSync) ProtoMessage() {}

func (x *ChunkSync) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkSync.ProtoReflect.Descriptor instead.
func (*ChunkSync) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{10}
}

func (x *ChunkSync) GetChunkX() int32 {
	if x != nil {
		return x.ChunkX
	}
	return 0
}

func (x *ChunkSync) GetChunkY() int32 {
	if x != nil {
		return x.ChunkY
	}
	return 0
}

func (x *ChunkSync) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *ChunkSync) GetReveals() []*RevealEvent {
	if x != nil {
		return x.Reveals
	}
	return nil
}

func (x *ChunkSync) GetFlags() []*FlagEvent {
	if x != nil {
		return x.Flags
	}
	return nil
}

type ScoreUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreUpdate) Reset() {
	*x = ScoreUpdate{}
	mi := &file_proto_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreUpdate) ProtoMessage() {}

func (x *ScoreUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreUpdate.ProtoReflect.Descriptor instead.
func (*ScoreUpdate) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ScoreUpdate) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Score         string                 `protobuf:"bytes,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_proto_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{12}
}

func (x *LeaderboardEntry) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *LeaderboardEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeaderboardEntry) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

type Leaderboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leaderboard) Reset() {
	*x = Leaderboard{}
	mi := &file_proto_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leaderboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leaderboard) ProtoMessage() {}

func (x *Leaderboard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leaderboard.ProtoReflect.Descriptor instead.
func (*Leaderboard) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{13}
}

func (x *Leaderboard) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Leaderboard) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Envelope_Hello
	//	*Envelope_Welcome
	//	*Envelope_Reveal
	//	*Envelope_RevealAck
	//	*Envelope_Flag
	//	*Envelope_FlagAck
	//	*Envelope_Subscribe
	//	*Envelope_Unsubscribe
	//	*Envelope_RevealEvent
	//	*Envelope_FlagEvent
	//	*Envelope_ChunkSync
	//	*Envelope_ScoreUpdate
	//	*Envelope_Leaderboard
	Msg           isEnvelope_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{14}
}

func (x *Envelope) GetMsg() isEnvelope_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Envelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Envelope) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *Envelope) GetReveal() *RevealRequest {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Reveal); ok {
			return x.Reveal
		}
	}
	return nil
}

func (x *Envelope) GetRevealAck() *RevealAck {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_RevealAck); ok {
			return x.RevealAck
		}
	}
	return nil
}

func (x *Envelope) GetFlag() *FlagRequest {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Flag); ok {
			return x.Flag
		}
	}
	return nil
}

func (x *Envelope) GetFlagAck() *FlagAck {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_FlagAck); ok {
			return x.FlagAck
		}
	}
	return nil
}

func (x *Envelope) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *Envelope) GetUnsubscribe() *Unsubscribe {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *Envelope) GetRevealEvent() *RevealEvent {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_RevealEvent); ok {
			return x.RevealEvent
		}
	}
	return nil
}

func (x *Envelope) GetFlagEvent() *FlagEvent {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_FlagEvent); ok {
			return x.FlagEvent
		}
	}
	return nil
}

func (x *Envelope) GetChunkSync() *ChunkSync {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_ChunkSync); ok {
			return x.ChunkSync
		}
	}
	return nil
}

func (x *Envelope) GetScoreUpdate() *ScoreUpdate {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_ScoreUpdate); ok {
			return x.ScoreUpdate
		}
	}
	return nil
}

func (x *Envelope) GetLeaderboard() *Leaderboard {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_Leaderboard); ok {
			return x.Leaderboard
		}
	}
	return nil
}

type isEnvelope_Msg interface {
	isEnvelope_Msg()
}

type Envelope_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type Envelope_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,2,opt,name=welcome,proto3,oneof"`
}

type Envelope_Reveal struct {
	Reveal *RevealRequest `protobuf:"bytes,3,opt,name=reveal,proto3,oneof"`
}

type Envelope_RevealAck struct {
	RevealAck *RevealAck `protobuf:"bytes,4,opt,name=reveal_ack,json=revealAck,proto3,oneof"`
}

type Envelope_Flag struct {
	Flag *FlagRequest `protobuf:"bytes,5,opt,name=flag,proto3,oneof"`
}

type Envelope_FlagAck struct {
	FlagAck *FlagAck `protobuf:"bytes,6,opt,name=flag_ack,json=flagAck,proto3,oneof"`
}

type Envelope_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,7,opt,name=subscribe,proto3,oneof"`
}

type Envelope_Unsubscribe struct {
	Unsubscribe *Unsubscribe `protobuf:"bytes,8,opt,name=unsubscribe,proto3,oneof"`
}

type Envelope_RevealEvent struct {
	RevealEvent *RevealEvent `protobuf:"bytes,9,opt,name=reveal_event,json=revealEvent,proto3,oneof"`
}

type Envelope_FlagEvent struct {
	FlagEvent *FlagEvent `protobuf:"bytes,10,opt,name=flag_event,json=flagEvent,proto3,oneof"`
}

type Envelope_ChunkSync struct {
	ChunkSync *ChunkSync `protobuf:"bytes,11,opt,name=chunk_sync,json=chunkSync,proto3,oneof"`
}

type Envelope_ScoreUpdate struct {
	ScoreUpdate *ScoreUpdate `protobuf:"bytes,12,opt,name=score_update,json=scoreUpdate,proto3,oneof"`
}

type Envelope_Leaderboard struct {
	Leaderboard *Leaderboard `protobuf:"bytes,13,opt,name=leaderboard,proto3,oneof"`
}

func (*Envelope_Hello) isEnvelope_Msg() {}

func (*Envelope_Welcome) isEnvelope_Msg() {}

func (*Envelope_Reveal) isEnvelope_Msg() {}

func (*Envelope_RevealAck) isEnvelope_Msg() {}

func (*Envelope_Flag) isEnvelope_Msg() {}

func (*Envelope_FlagAck) isEnvelope_Msg() {}

func (*Envelope_Subscribe) isEnvelope_Msg() {}

func (*Envelope_Unsubscribe) isEnvelope_Msg() {}

func (*Envelope_RevealEvent) isEnvelope_Msg() {}

func (*Envelope_FlagEvent) isEnvelope_Msg() {}

func (*Envelope_ChunkSync) isEnvelope_Msg() {}

func (*Envelope_ScoreUpdate) isEnvelope_Msg() {}

func (*Envelope_Leaderboard) isEnvelope_Msg() {}

var File_proto_messages_proto protoreflect.FileDescriptor

const file_proto_messages_proto_rawDesc = "" +
	"\n" +
	"\x14proto/messages.proto\x12\x02pb\"N\n" +
	"\x05Hello\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\"P\n" +
	"\aWelcome\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\"]\n" +
	"\rRevealRequest\x12\x17\n" +
	"\achunk_x\x18\x01 \x01(\x05R\x06chunkX\x12\x17\n" +
	"\achunk_y\x18\x02 \x01(\x05R\x06chunkY\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\"\x1b\n" +
	"\tRevealAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"[\n" +
	"\vFlagRequest\x12\x17\n" +
	"\achunk_x\x18\x01 \x01(\x05R\x06chunkX\x12\x17\n" +
	"\achunk_y\x18\x02 \x01(\x05R\x06chunkY\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\"\x19\n" +
	"\aFlagAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"=\n" +
	"\tSubscribe\x12\x17\n" +
	"\achunk_x\x18\x01 \x01(\x05R\x06chunkX\x12\x17\n" +
	"\achunk_y\x18\x02 \x01(\x05R\x06chunkY\"?\n" +
	"\vUnsubscribe\x12\x17\n" +
	"\achunk_x\x18\x01 \x01(\x05R\x06chunkX\x12\x17\n" +
	"\achunk_y\x18\x02 \x01(\x05R\x06chunkY\"x\n" +
	"\vRevealEvent\x12\x17\n" +
	"\achunk_x\x18\x01 \x01(\x05R\x06chunkX\x12\x17\n" +
	"\achunk_y\x18\x02 \x01(\x05R\x06chunkY\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x1b\n" +
	"\tplayer_id\x18\x05 \x01(\x05R\bplayerId\"\x8c\x01\n" +
	"\tFlagEvent\x12\x17\n" +
	"\achunk_x\x18\x01 \x01(\x05R\x06chunkX\x12\x17\n" +
	"\achunk_y\x18\x02 \x01(\x05R\x06chunkY\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x1b\n" +
	"\tplayer_id\x18\x05 \x01(\x05R\bplayerId\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\"\xa1\x01\n" +
	"\tChunkSync\x12\x17\n" +
	"\achunk_x\x18\x01 \x01(\x05R\x06chunkX\x12\x17\n" +
	"\achunk_y\x18\x02 \x01(\x05R\x06chunkY\x12\x12\n" +
	"\x04seed\x18\x03 \x01(\x04R\x04seed\x12)\n" +
	"\areveals\x18\x04 \x03(\v2\x0f.pb.RevealEventR\areveals\x12#\n" +
	"\x05flags\x18\x05 \x03(\v2\r.pb.FlagEventR\x05flags\"#\n" +
	"\vScoreUpdate\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\"Y\n" +
	"\x10LeaderboardEntry\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x03 \x01(\tR\x05score\"W\n" +
	"\vLeaderboard\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12.\n" +
	"\aentries\x18\x02 \x03(\v2\x14.pb.LeaderboardEntryR\aentries\"\xf0\x04\n" +
	"\bEnvelope\x12!\n" +
	"\x05hello\x18\x01 \x01(\v2\t.pb.HelloH\x00R\x05hello\x12'\n" +
	"\awelcome\x18\x02 \x01(\v2\v.pb.WelcomeH\x00R\awelcome\x12+\n" +
	"\x06reveal\x18\x03 \x01(\v2\x11.pb.RevealRequestH\x00R\x06reveal\x12.\n" +
	"\n" +
	"reveal_ack\x18\x04 \x01(\v2\r.pb.RevealAckH\x00R\trevealAck\x12%\n" +
	"\x04flag\x18\x05 \x01(\v2\x0f.pb.FlagRequestH\x00R\x04flag\x12(\n" +
	"\bflag_ack\x18\x06 \x01(\v2\v.pb.FlagAckH\x00R\aflagAck\x12-\n" +
	"\tsubscribe\x18\a \x01(\v2\r.pb.SubscribeH\x00R\tsubscribe\x123\n" +
	"\vunsubscribe\x18\b \x01(\v2\x0f.pb.UnsubscribeH\x00R\vunsubscribe\x124\n" +
	"\freveal_event\x18\t \x01(\v2\x0f.pb.RevealEventH\x00R\vrevealEvent\x12.\n" +
	"\n" +
	"flag_event\x18\n" +
	" \x01(\v2\r.pb.FlagEventH\x00R\tflagEvent\x12.\n" +
	"\n" +
	"chunk_sync\x18\v \x01(\v2\r.pb.ChunkSyncH\x00R\tchunkSync\x124\n" +
	"\fscore_update\x18\f \x01(\v2\x0f.pb.ScoreUpdateH\x00R\vscoreUpdate\x123\n" +
	"\vleaderboard\x18\r \x01(\v2\x0f.pb.LeaderboardH\x00R\vleaderboardB\x05\n" +
	"\x03msgB\x1cZ\x1ainfinite-minesweeper/pb;pbb\x06proto3"

var (
	file_proto_messages_proto_rawDescOnce sync.Once
	file_proto_messages_proto_rawDescData []byte
)

func file_proto_messages_proto_rawDescGZIP() []byte {
	file_proto_messages_proto_rawDescOnce.Do(func() {
		file_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)))
	})
	return file_proto_messages_proto_rawDescData
}

var file_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_messages_proto_goTypes = []any{
	(*Hello)(nil),            // 0: pb.Hello
	(*Welcome)(nil),          // 1: pb.Welcome
	(*RevealRequest)(nil),    // 2: pb.RevealRequest
	(*RevealAck)(nil),        // 3: pb.RevealAck
	(*FlagRequest)(nil),      // 4: pb.FlagRequest
	(*FlagAck)(nil),          // 5: pb.FlagAck
	(*Subscribe)(nil),        // 6: pb.Subscribe
	(*Unsubscribe)(nil),      // 7: pb.Unsubscribe
	(*RevealEvent)(nil),      // 8: pb.RevealEvent
	(*FlagEvent)(nil),        // 9: pb.FlagEvent
	(*ChunkSync)(nil),        // 10: pb.ChunkSync
	(*ScoreUpdate)(nil),      // 11: pb.ScoreUpdate
	(*LeaderboardEntry)(nil), // 12: pb.LeaderboardEntry
	(*Leaderboard)(nil),      // 13: pb.Leaderboard
	(*Envelope)(nil),         // 14: pb.Envelope
}
var file_proto_messages_proto_depIdxs = []int32{
	8,  // 0: pb.ChunkSync.reveals:type_name -> pb.RevealEvent
	9,  // 1: pb.ChunkSync.flags:type_name -> pb.FlagEvent
	12, // 2: pb.Leaderboard.entries:type_name -> pb.LeaderboardEntry
	0,  // 3: pb.Envelope.hello:type_name -> pb.Hello
	1,  // 4: pb.Envelope.welcome:type_name -> pb.Welcome
	2,  // 5: pb.Envelope.reveal:type_name -> pb.RevealRequest
	3,  // 6: pb.Envelope.reveal_ack:type_name -> pb.RevealAck
	4,  // 7: pb.Envelope.flag:type_name -> pb.FlagRequest
	5,  // 8: pb.Envelope.flag_ack:type_name -> pb.FlagAck
	6,  // 9: pb.Envelope.subscribe:type_name -> pb.Subscribe
	7,  // 10: pb.Envelope.unsubscribe:type_name -> pb.Unsubscribe
	8,  // 11: pb.Envelope.reveal_event:type_name -> pb.RevealEvent
	9,  // 12: pb.Envelope.flag_event:type_name -> pb.FlagEvent
	10, // 13: pb.Envelope.chunk_sync:type_name -> pb.ChunkSync
	11, // 14: pb.Envelope.score_update:type_name -> pb.ScoreUpdate
	13, // 15: pb.Envelope.leaderboard:type_name -> pb.Leaderboard
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_messages_proto_init() }
func file_proto_messages_proto_init() {
	if File_proto_messages_proto != nil {
		return
	}
	file_proto_messages_proto_msgTypes[14].OneofWrappers = []any{
		(*Envelope_Hello)(nil),
		(*Envelope_Welcome)(nil),
		(*Envelope_Reveal)(nil),
		(*Envelope_RevealAck)(nil),
		(*Envelope_Flag)(nil),
		(*Envelope_FlagAck)(nil),
		(*Envelope_Subscribe)(nil),
		(*Envelope_Unsubscribe)(nil),
		(*Envelope_RevealEvent)(nil),
		(*Envelope_FlagEvent)(nil),
		(*Envelope_ChunkSync)(nil),
		(*Envelope_ScoreUpdate)(nil),
		(*Envelope_Leaderboard)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_messages_proto_goTypes,
		DependencyIndexes: file_proto_messages_proto_depIdxs,
		MessageInfos:      file_proto_messages_proto_msgTypes,
	}.Build()
	File_proto_messages_proto = out.File
	file_proto_messages_proto_goTypes = nil
	file_proto_messages_proto_depIdxs = nil
}
