// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *ChunkID) Reset() {
	*x = ChunkID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChunkID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkID) ProtoMessage() {}

func (x *ChunkID) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkID.ProtoReflect.Descriptor instead.
func (*ChunkID) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkID) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ChunkID) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Reveal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkId  *ChunkID `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	X        int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y        int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	PlayerId int32    `protobuf:"varint,4,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *Reveal) Reset() {
	*x = Reveal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reveal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reveal) ProtoMessage() {}

func (x *Reveal) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reveal.ProtoReflect.Descriptor instead.
func (*Reveal) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Reveal) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *Reveal) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Reveal) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Reveal) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type Flag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkId  *ChunkID `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	X        int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y        int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	PlayerId int32    `protobuf:"varint,4,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Color    string   `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *Flag) Reset() {
	*x = Flag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Flag) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *Flag) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Flag) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Flag) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Flag) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int32  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color    string `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *Hello) Reset() {
	*x = Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Hello) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hello) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type Welcome struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int32 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Welcome) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type RevealMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkId *ChunkID `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	X       int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y       int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *RevealMessage) Reset() {
	*x = RevealMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevealMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealMessage) ProtoMessage() {}

func (x *RevealMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealMessage.ProtoReflect.Descriptor instead.
func (*RevealMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *RevealMessage) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *RevealMessage) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RevealMessage) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type FlagMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkId *ChunkID `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	X       int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y       int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *FlagMessage) Reset() {
	*x = FlagMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlagMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagMessage) ProtoMessage() {}

func (x *FlagMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagMessage.ProtoReflect.Descriptor instead.
func (*FlagMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *FlagMessage) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *FlagMessage) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FlagMessage) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Subscribe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkId *ChunkID `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *Subscribe) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

type Unsubscribe struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkId *ChunkID `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
}

func (x *Unsubscribe) Reset() {
	*x = Unsubscribe{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsubscribe) ProtoMessage() {}

func (x *Unsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsubscribe.ProtoReflect.Descriptor instead.
func (*Unsubscribe) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *Unsubscribe) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

type ChunkSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkId *ChunkID  `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Seed    uint64    `protobuf:"varint,2,opt,name=seed,proto3" json:"seed,omitempty"`
	Reveals []*Reveal `protobuf:"bytes,3,rep,name=reveals,proto3" json:"reveals,omitempty"`
	Flags   []*Flag   `protobuf:"bytes,4,rep,name=flags,proto3" json:"flags,omitempty"`
}

func (x *ChunkSync) Reset() {
	*x = ChunkSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChunkSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkSync) ProtoMessage() {}

func (x *ChunkSync) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkSync.ProtoReflect.Descriptor instead.
func (*ChunkSync) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ChunkSync) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *ChunkSync) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *ChunkSync) GetReveals() []*Reveal {
	if x != nil {
		return x.Reveals
	}
	return nil
}

func (x *ChunkSync) GetFlags() []*Flag {
	if x != nil {
		return x.Flags
	}
	return nil
}

type RevealAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *RevealAck) Reset() {
	*x = RevealAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevealAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealAck) ProtoMessage() {}

func (x *RevealAck) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealAck.ProtoReflect.Descriptor instead.
func (*RevealAck) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *RevealAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type FlagAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *FlagAck) Reset() {
	*x = FlagAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlagAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagAck) ProtoMessage() {}

func (x *FlagAck) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagAck.ProtoReflect.Descriptor instead.
func (*FlagAck) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *FlagAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int32  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Score    string `protobuf:"bytes,3,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *LeaderboardEntry) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *LeaderboardEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeaderboardEntry) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

type Leaderboard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint64              `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Entries []*LeaderboardEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *Leaderboard) Reset() {
	*x = Leaderboard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Leaderboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leaderboard) ProtoMessage() {}

func (x *Leaderboard) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leaderboard.ProtoReflect.Descriptor instead.
func (*Leaderboard) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *Leaderboard) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Leaderboard) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ScoreUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score int32 `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *ScoreUpdate) Reset() {
	*x = ScoreUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreUpdate) ProtoMessage() {}

func (x *ScoreUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreUpdate.ProtoReflect.Descriptor instead.
func (*ScoreUpdate) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *ScoreUpdate) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Envelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*Envelope_Hello
	//	*Envelope_Welcome
	//	*Envelope_Reveal
	//	*Envelope_RevealAck
	//	*Envelope_Flag
	//	*Envelope_FlagAck
	//	*Envelope_Subscribe
	//	*Envelope_Unsubscribe
	//	*Envelope_ChunkSync
	//	*Envelope_Leaderboard
	//	*Envelope_BroadcastReveal
	//	*Envelope_BroadcastFlag
	//	*Envelope_ScoreUpdate
	Msg isEnvelope_Msg `protobuf_oneof:"msg"`
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

func (m *Envelope) GetMsg() isEnvelope_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *Envelope) GetHello() *Hello {
	if x, ok := x.GetMsg().(*Envelope_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *Envelope) GetWelcome() *Welcome {
	if x, ok := x.GetMsg().(*Envelope_Welcome); ok {
		return x.Welcome
	}
	return nil
}

func (x *Envelope) GetReveal() *RevealMessage {
	if x, ok := x.GetMsg().(*Envelope_Reveal); ok {
		return x.Reveal
	}
	return nil
}

func (x *Envelope) GetRevealAck() *RevealAck {
	if x, ok := x.GetMsg().(*Envelope_RevealAck); ok {
		return x.RevealAck
	}
	return nil
}

func (x *Envelope) GetFlag() *FlagMessage {
	if x, ok := x.GetMsg().(*Envelope_Flag); ok {
		return x.Flag
	}
	return nil
}

func (x *Envelope) GetFlagAck() *FlagAck {
	if x, ok := x.GetMsg().(*Envelope_FlagAck); ok {
		return x.FlagAck
	}
	return nil
}

func (x *Envelope) GetSubscribe() *Subscribe {
	if x, ok := x.GetMsg().(*Envelope_Subscribe); ok {
		return x.Subscribe
	}
	return nil
}

func (x *Envelope) GetUnsubscribe() *Unsubscribe {
	if x, ok := x.GetMsg().(*Envelope_Unsubscribe); ok {
		return x.Unsubscribe
	}
	return nil
}

func (x *Envelope) GetChunkSync() *ChunkSync {
	if x, ok := x.GetMsg().(*Envelope_ChunkSync); ok {
		return x.ChunkSync
	}
	return nil
}

func (x *Envelope) GetLeaderboard() *Leaderboard {
	if x, ok := x.GetMsg().(*Envelope_Leaderboard); ok {
		return x.Leaderboard
	}
	return nil
}

func (x *Envelope) GetBroadcastReveal() *Reveal {
	if x, ok := x.GetMsg().(*Envelope_BroadcastReveal); ok {
		return x.BroadcastReveal
	}
	return nil
}

func (x *Envelope) GetBroadcastFlag() *Flag {
	if x, ok := x.GetMsg().(*Envelope_BroadcastFlag); ok {
		return x.BroadcastFlag
	}
	return nil
}

func (x *Envelope) GetScoreUpdate() *ScoreUpdate {
	if x, ok := x.GetMsg().(*Envelope_ScoreUpdate); ok {
		return x.ScoreUpdate
	}
	return nil
}

type isEnvelope_Msg interface {
	isEnvelope_Msg()
}

type Envelope_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type Envelope_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,2,opt,name=welcome,proto3,oneof"`
}

type Envelope_Reveal struct {
	Reveal *RevealMessage `protobuf:"bytes,3,opt,name=reveal,proto3,oneof"`
}

type Envelope_RevealAck struct {
	RevealAck *RevealAck `protobuf:"bytes,4,opt,name=reveal_ack,json=revealAck,proto3,oneof"`
}

type Envelope_Flag struct {
	Flag *FlagMessage `protobuf:"bytes,5,opt,name=flag,proto3,oneof"`
}

type Envelope_FlagAck struct {
	FlagAck *FlagAck `protobuf:"bytes,6,opt,name=flag_ack,json=flagAck,proto3,oneof"`
}

type Envelope_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,7,opt,name=subscribe,proto3,oneof"`
}

type Envelope_Unsubscribe struct {
	Unsubscribe *Unsubscribe `protobuf:"bytes,8,opt,name=unsubscribe,proto3,oneof"`
}

type Envelope_ChunkSync struct {
	ChunkSync *ChunkSync `protobuf:"bytes,9,opt,name=chunk_sync,json=chunkSync,proto3,oneof"`
}

type Envelope_Leaderboard struct {
	Leaderboard *Leaderboard `protobuf:"bytes,10,opt,name=leaderboard,proto3,oneof"`
}

type Envelope_BroadcastReveal struct {
	BroadcastReveal *Reveal `protobuf:"bytes,11,opt,name=broadcast_reveal,json=broadcastReveal,proto3,oneof"`
}

type Envelope_BroadcastFlag struct {
	BroadcastFlag *Flag `protobuf:"bytes,12,opt,name=broadcast_flag,json=broadcastFlag,proto3,oneof"`
}

type Envelope_ScoreUpdate struct {
	ScoreUpdate *ScoreUpdate `protobuf:"bytes,13,opt,name=score_update,json=scoreUpdate,proto3,oneof"`
}

func (*Envelope_Hello) isEnvelope_Msg() {}

func (*Envelope_Welcome) isEnvelope_Msg() {}

func (*Envelope_Reveal) isEnvelope_Msg() {}

func (*Envelope_RevealAck) isEnvelope_Msg() {}

func (*Envelope_Flag) isEnvelope_Msg() {}

func (*Envelope_FlagAck) isEnvelope_Msg() {}

func (*Envelope_Subscribe) isEnvelope_Msg() {}

func (*Envelope_Unsubscribe) isEnvelope_Msg() {}

func (*Envelope_ChunkSync) isEnvelope_Msg() {}

func (*Envelope_Leaderboard) isEnvelope_Msg() {}

func (*Envelope_BroadcastReveal) isEnvelope_Msg() {}

func (*Envelope_BroadcastFlag) isEnvelope_Msg() {}

func (*Envelope_ScoreUpdate) isEnvelope_Msg() {}

var File_messages_proto protoreflect.FileDescriptor

var file_messages_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x22, 0x25, 0x0a,
	0x07, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x44, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x79, 0x22, 0x72, 0x0a, 0x06, 0x52, 0x65, 0x76, 0x65, 0x61, 0x6c, 0x12, 0x2f,
	0x0a, 0x08, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x49, 0x44, 0x52, 0x07, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x64, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x86, 0x01, 0x0a, 0x04, 0x46, 0x6c, 0x61,
	0x67, 0x12, 0x2f, 0x0a, 0x08, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x44, 0x52, 0x07, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x22, 0x4e, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x22, 0x26, 0x0a, 0x07, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5c, 0x0a, 0x0d, 0x52, 0x65, 0x76,
	0x65, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x63, 0x68,
	0x75, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d,
	0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x49, 0x44, 0x52, 0x07, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0x5a, 0x0a, 0x0b, 0x46, 0x6c, 0x61, 0x67, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73,
	0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x44, 0x52, 0x07,
	0x63, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x79, 0x22, 0x3c, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x12, 0x2f, 0x0a, 0x08, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x44, 0x52, 0x07, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x49,
	0x64, 0x22, 0x3e, 0x0a, 0x0b, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x12, 0x2f, 0x0a, 0x08, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x44, 0x52, 0x07, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x49,
	0x64, 0x22, 0xa8, 0x01, 0x0a, 0x09, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x79, 0x6e, 0x63, 0x12,
	0x2f, 0x0a, 0x08, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x44, 0x52, 0x07, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x73, 0x65, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x07, 0x72, 0x65, 0x76, 0x65, 0x61, 0x6c, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x76, 0x65, 0x61, 0x6c, 0x52, 0x07, 0x72, 0x65, 0x76, 0x65,
	0x61, 0x6c, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x22, 0x1b, 0x0a, 0x09,
	0x52, 0x65, 0x76, 0x65, 0x61, 0x6c, 0x41, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x19, 0x0a, 0x07, 0x46, 0x6c, 0x61,
	0x67, 0x41, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x22, 0x59, 0x0a, 0x10, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22,
	0x60, 0x0a, 0x0b, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x69, 0x6e, 0x65,
	0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x22, 0x23, 0x0a, 0x0b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0xeb, 0x05, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c,
	0x6f, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12,
	0x30, 0x0a, 0x07, 0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x57,
	0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x07, 0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d,
	0x65, 0x12, 0x34, 0x0a, 0x06, 0x72, 0x65, 0x76, 0x65, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x76, 0x65, 0x61, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x06, 0x72, 0x65, 0x76, 0x65, 0x61, 0x6c, 0x12, 0x37, 0x0a, 0x0a, 0x72, 0x65, 0x76, 0x65, 0x61,
	0x6c, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x69,
	0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x76, 0x65, 0x61, 0x6c,
	0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x09, 0x72, 0x65, 0x76, 0x65, 0x61, 0x6c, 0x41, 0x63, 0x6b,
	0x12, 0x2e, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x46, 0x6c, 0x61,
	0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67,
	0x12, 0x31, 0x0a, 0x08, 0x66, 0x6c, 0x61, 0x67, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x2e, 0x46, 0x6c, 0x61, 0x67, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x07, 0x66, 0x6c, 0x61, 0x67,
	0x41, 0x63, 0x6b, 0x12, 0x36, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48, 0x00,
	0x52, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x75,
	0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x55,
	0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x6e,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x53, 0x79, 0x6e, 0x63, 0x48, 0x00, 0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x79,
	0x6e, 0x63, 0x12, 0x3c, 0x0a, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x48, 0x00, 0x52, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x12, 0x40, 0x0a, 0x10, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x5f, 0x72, 0x65,
	0x76, 0x65, 0x61, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x69, 0x6e,
	0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x76, 0x65, 0x61, 0x6c, 0x48,
	0x00, 0x52, 0x0f, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x65, 0x76, 0x65,
	0x61, 0x6c, 0x12, 0x3a, 0x0a, 0x0e, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x5f,
	0x66, 0x6c, 0x61, 0x67, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x69, 0x6e,
	0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x48, 0x00, 0x52,
	0x0d, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x3d,
	0x0a, 0x0c, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70,
	0x65, 0x72, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x48, 0x00,
	0x52, 0x0b, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x05, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x42, 0x1c, 0x5a, 0x1a, 0x69, 0x6e, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x65,
	0x2d, 0x6d, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData = file_messages_proto_rawDesc
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_proto_rawDescData)
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_messages_proto_goTypes = []interface{}{
	(*ChunkID)(nil),          // 0: minesweeper.ChunkID
	(*Reveal)(nil),           // 1: minesweeper.Reveal
	(*Flag)(nil),             // 2: minesweeper.Flag
	(*Hello)(nil),            // 3: minesweeper.Hello
	(*Welcome)(nil),          // 4: minesweeper.Welcome
	(*RevealMessage)(nil),    // 5: minesweeper.RevealMessage
	(*FlagMessage)(nil),      // 6: minesweeper.FlagMessage
	(*Subscribe)(nil),        // 7: minesweeper.Subscribe
	(*Unsubscribe)(nil),      // 8: minesweeper.Unsubscribe
	(*ChunkSync)(nil),        // 9: minesweeper.ChunkSync
	(*RevealAck)(nil),        // 10: minesweeper.RevealAck
	(*FlagAck)(nil),          // 11: minesweeper.FlagAck
	(*LeaderboardEntry)(nil), // 12: minesweeper.LeaderboardEntry
	(*Leaderboard)(nil),      // 13: minesweeper.Leaderboard
	(*ScoreUpdate)(nil),      // 14: minesweeper.ScoreUpdate
	(*Envelope)(nil),         // 15: minesweeper.Envelope
}
var file_messages_proto_depIdxs = []int32{
	0,  // 0: minesweeper.Reveal.chunk_id:type_name -> minesweeper.ChunkID
	0,  // 1: minesweeper.Flag.chunk_id:type_name -> minesweeper.ChunkID
	0,  // 2: minesweeper.RevealMessage.chunk_id:type_name -> minesweeper.ChunkID
	0,  // 3: minesweeper.FlagMessage.chunk_id:type_name -> minesweeper.ChunkID
	0,  // 4: minesweeper.Subscribe.chunk_id:type_name -> minesweeper.ChunkID
	0,  // 5: minesweeper.Unsubscribe.chunk_id:type_name -> minesweeper.ChunkID
	0,  // 6: minesweeper.ChunkSync.chunk_id:type_name -> minesweeper.ChunkID
	1,  // 7: minesweeper.ChunkSync.reveals:type_name -> minesweeper.Reveal
	2,  // 8: minesweeper.ChunkSync.flags:type_name -> minesweeper.Flag
	12, // 9: minesweeper.Leaderboard.entries:type_name -> minesweeper.LeaderboardEntry
	3,  // 10: minesweeper.Envelope.hello:type_name -> minesweeper.Hello
	4,  // 11: minesweeper.Envelope.welcome:type_name -> minesweeper.Welcome
	5,  // 12: minesweeper.Envelope.reveal:type_name -> minesweeper.RevealMessage
	10, // 13: minesweeper.Envelope.reveal_ack:type_name -> minesweeper.RevealAck
	6,  // 14: minesweeper.Envelope.flag:type_name -> minesweeper.FlagMessage
	11, // 15: minesweeper.Envelope.flag_ack:type_name -> minesweeper.FlagAck
	7,  // 16: minesweeper.Envelope.subscribe:type_name -> minesweeper.Subscribe
	8,  // 17: minesweeper.Envelope.unsubscribe:type_name -> minesweeper.Unsubscribe
	9,  // 18: minesweeper.Envelope.chunk_sync:type_name -> minesweeper.ChunkSync
	13, // 19: minesweeper.Envelope.leaderboard:type_name -> minesweeper.Leaderboard
	1,  // 20: minesweeper.Envelope.broadcast_reveal:type_name -> minesweeper.Reveal
	2,  // 21: minesweeper.Envelope.broadcast_flag:type_name -> minesweeper.Flag
	14, // 22: minesweeper.Envelope.score_update:type_name -> minesweeper.ScoreUpdate
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChunkID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reveal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Flag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Welcome); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevealMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlagMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Subscribe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unsubscribe); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChunkSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevealAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlagAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderboardEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Leaderboard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoreUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Envelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_messages_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*Envelope_Hello)(nil),
		(*Envelope_Welcome)(nil),
		(*Envelope_Reveal)(nil),
		(*Envelope_RevealAck)(nil),
		(*Envelope_Flag)(nil),
		(*Envelope_FlagAck)(nil),
		(*Envelope_Subscribe)(nil),
		(*Envelope_Unsubscribe)(nil),
		(*Envelope_ChunkSync)(nil),
		(*Envelope_Leaderboard)(nil),
		(*Envelope_BroadcastReveal)(nil),
		(*Envelope_BroadcastFlag)(nil),
		(*Envelope_ScoreUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_rawDesc = nil
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
