// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkID) Reset() {
	*x = ChunkID{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkID) ProtoMessage() {}

func (x *ChunkID) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkID.ProtoReflect.Descriptor instead.
func (*ChunkID) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkID) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ChunkID) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type RevealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkID               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealRequest) Reset() {
	*x = RevealRequest{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealRequest) ProtoMessage() {}

func (x *RevealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealRequest.ProtoReflect.Descriptor instead.
func (*RevealRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *RevealRequest) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *RevealRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RevealRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkID               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkID               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *UnsubscribeRequest) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

type SeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkID               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedRequest) Reset() {
	*x = SeedRequest{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedRequest) ProtoMessage() {}

func (x *SeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedRequest.ProtoReflect.Descriptor instead.
func (*SeedRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *SeedRequest) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

type SeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkID               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Seed          uint64                 `protobuf:"varint,2,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedResponse) Reset() {
	*x = SeedResponse{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedResponse) ProtoMessage() {}

func (x *SeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedResponse.ProtoReflect.Descriptor instead.
func (*SeedResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *SeedResponse) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *SeedResponse) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type Reveal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkID               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	PlayerId      int32                  `protobuf:"varint,4,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reveal) Reset() {
	*x = Reveal{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reveal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reveal) ProtoMessage() {}

func (x *Reveal) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reveal.ProtoReflect.Descriptor instead.
func (*Reveal) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *Reveal) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *Reveal) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Reveal) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Reveal) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type ChunkSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkID               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Seed          uint64                 `protobuf:"varint,2,opt,name=seed,proto3" json:"seed,omitempty"`
	Reveals       []*Reveal              `protobuf:"bytes,3,rep,name=reveals,proto3" json:"reveals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkSync) Reset() {
	*x = ChunkSync{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkSync) ProtoMessage() {}

func (x *ChunkSync) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkSync.ProtoReflect.Descriptor instead.
func (*ChunkSync) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ChunkSync) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *ChunkSync) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *ChunkSync) GetReveals() []*Reveal {
	if x != nil {
		return x.Reveals
	}
	return nil
}

type RevealAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       *ChunkID               `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Ok            bool                   `protobuf:"varint,4,opt,name=ok,proto3" json:"ok,omitempty"`
	Scorer        int32                  `protobuf:"varint,5,opt,name=scorer,proto3" json:"scorer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevealAck) Reset() {
	*x = RevealAck{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevealAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealAck) ProtoMessage() {}

func (x *RevealAck) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealAck.ProtoReflect.Descriptor instead.
func (*RevealAck) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *RevealAck) GetChunkId() *ChunkID {
	if x != nil {
		return x.ChunkId
	}
	return nil
}

func (x *RevealAck) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RevealAck) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *RevealAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RevealAck) GetScorer() int32 {
	if x != nil {
		return x.Scorer
	}
	return 0
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int32                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Score         string                 `protobuf:"bytes,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *LeaderboardEntry) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *LeaderboardEntry) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

type Leaderboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leaderboard) Reset() {
	*x = Leaderboard{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leaderboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leaderboard) ProtoMessage() {}

func (x *Leaderboard) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leaderboard.ProtoReflect.Descriptor instead.
func (*Leaderboard) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *Leaderboard) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Leaderboard) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientMessage_Reveal
	//	*ClientMessage_Subscribe
	//	*ClientMessage_Unsubscribe
	//	*ClientMessage_Seed
	Msg           isClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ClientMessage) GetMsg() isClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientMessage) GetReveal() *RevealRequest {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Reveal); ok {
			return x.Reveal
		}
	}
	return nil
}

func (x *ClientMessage) GetSubscribe() *SubscribeRequest {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *ClientMessage) GetUnsubscribe() *UnsubscribeRequest {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *ClientMessage) GetSeed() *SeedRequest {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Seed); ok {
			return x.Seed
		}
	}
	return nil
}

type isClientMessage_Msg interface {
	isClientMessage_Msg()
}

type ClientMessage_Reveal struct {
	Reveal *RevealRequest `protobuf:"bytes,1,opt,name=reveal,proto3,oneof"`
}

type ClientMessage_Subscribe struct {
	Subscribe *SubscribeRequest `protobuf:"bytes,2,opt,name=subscribe,proto3,oneof"`
}

type ClientMessage_Unsubscribe struct {
	Unsubscribe *UnsubscribeRequest `protobuf:"bytes,3,opt,name=unsubscribe,proto3,oneof"`
}

type ClientMessage_Seed struct {
	Seed *SeedRequest `protobuf:"bytes,4,opt,name=seed,proto3,oneof"`
}

func (*ClientMessage_Reveal) isClientMessage_Msg() {}

func (*ClientMessage_Subscribe) isClientMessage_Msg() {}

func (*ClientMessage_Unsubscribe) isClientMessage_Msg() {}

func (*ClientMessage_Seed) isClientMessage_Msg() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_Reveal
	//	*ServerMessage_RevealAck
	//	*ServerMessage_Seed
	//	*ServerMessage_ChunkSync
	//	*ServerMessage_Leaderboard
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetReveal() *Reveal {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Reveal); ok {
			return x.Reveal
		}
	}
	return nil
}

func (x *ServerMessage) GetRevealAck() *RevealAck {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_RevealAck); ok {
			return x.RevealAck
		}
	}
	return nil
}

func (x *ServerMessage) GetSeed() *SeedResponse {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Seed); ok {
			return x.Seed
		}
	}
	return nil
}

func (x *ServerMessage) GetChunkSync() *ChunkSync {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_ChunkSync); ok {
			return x.ChunkSync
		}
	}
	return nil
}

func (x *ServerMessage) GetLeaderboard() *Leaderboard {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Leaderboard); ok {
			return x.Leaderboard
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_Reveal struct {
	Reveal *Reveal `protobuf:"bytes,1,opt,name=reveal,proto3,oneof"`
}

type ServerMessage_RevealAck struct {
	RevealAck *RevealAck `protobuf:"bytes,2,opt,name=reveal_ack,json=revealAck,proto3,oneof"`
}

type ServerMessage_Seed struct {
	Seed *SeedResponse `protobuf:"bytes,3,opt,name=seed,proto3,oneof"`
}

type ServerMessage_ChunkSync struct {
	ChunkSync *ChunkSync `protobuf:"bytes,4,opt,name=chunk_sync,json=chunkSync,proto3,oneof"`
}

type ServerMessage_Leaderboard struct {
	Leaderboard *Leaderboard `protobuf:"bytes,5,opt,name=leaderboard,proto3,oneof"`
}

func (*ServerMessage_Reveal) isServerMessage_Msg() {}

func (*ServerMessage_RevealAck) isServerMessage_Msg() {}

func (*ServerMessage_Seed) isServerMessage_Msg() {}

func (*ServerMessage_ChunkSync) isServerMessage_Msg() {}

func (*ServerMessage_Leaderboard) isServerMessage_Msg() {}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\"%\n" +
	"\aChunkID\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"P\n" +
	"\rRevealRequest\x12#\n" +
	"\bchunk_id\x18\x01 \x01(\v2\b.ChunkIDR\achunkId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"7\n" +
	"\x10SubscribeRequest\x12#\n" +
	"\bchunk_id\x18\x01 \x01(\v2\b.ChunkIDR\achunkId\"9\n" +
	"\x12UnsubscribeRequest\x12#\n" +
	"\bchunk_id\x18\x01 \x01(\v2\b.ChunkIDR\achunkId\"2\n" +
	"\vSeedRequest\x12#\n" +
	"\bchunk_id\x18\x01 \x01(\v2\b.ChunkIDR\achunkId\"G\n" +
	"\fSeedResponse\x12#\n" +
	"\bchunk_id\x18\x01 \x01(\v2\b.ChunkIDR\achunkId\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\x04R\x04seed\"f\n" +
	"\x06Reveal\x12#\n" +
	"\bchunk_id\x18\x01 \x01(\v2\b.ChunkIDR\achunkId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x1b\n" +
	"\tplayer_id\x18\x04 \x01(\x05R\bplayerId\"g\n" +
	"\tChunkSync\x12#\n" +
	"\bchunk_id\x18\x01 \x01(\v2\b.ChunkIDR\achunkId\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\x04R\x04seed\x12!\n" +
	"\areveals\x18\x03 \x03(\v2\a.RevealR\areveals\"t\n" +
	"\tRevealAck\x12#\n" +
	"\bchunk_id\x18\x01 \x01(\v2\b.ChunkIDR\achunkId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x0e\n" +
	"\x02ok\x18\x04 \x01(\bR\x02ok\x12\x16\n" +
	"\x06scorer\x18\x05 \x01(\x05R\x06scorer\"E\n" +
	"\x10LeaderboardEntry\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x05R\bplayerId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\tR\x05score\"T\n" +
	"\vLeaderboard\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12+\n" +
	"\aentries\x18\x02 \x03(\v2\x11.LeaderboardEntryR\aentries\"\xd0\x01\n" +
	"\rClientMessage\x12(\n" +
	"\x06reveal\x18\x01 \x01(\v2\x0e.RevealRequestH\x00R\x06reveal\x121\n" +
	"\tsubscribe\x18\x02 \x01(\v2\x11.SubscribeRequestH\x00R\tsubscribe\x127\n" +
	"\vunsubscribe\x18\x03 \x01(\v2\x13.UnsubscribeRequestH\x00R\vunsubscribe\x12\"\n" +
	"\x04seed\x18\x04 \x01(\v2\f.SeedRequestH\x00R\x04seedB\x05\n" +
	"\x03msg\"\xea\x01\n" +
	"\rServerMessage\x12!\n" +
	"\x06reveal\x18\x01 \x01(\v2\a.RevealH\x00R\x06reveal\x12+\n" +
	"\n" +
	"reveal_ack\x18\x02 \x01(\v2\n" +
	".RevealAckH\x00R\trevealAck\x12#\n" +
	"\x04seed\x18\x03 \x01(\v2\r.SeedResponseH\x00R\x04seed\x12+\n" +
	"\n" +
	"chunk_sync\x18\x04 \x01(\v2\n" +
	".ChunkSyncH\x00R\tchunkSync\x120\n" +
	"\vleaderboard\x18\x05 \x01(\v2\f.LeaderboardH\x00R\vleaderboardB\x05\n" +
	"\x03msgB\x19Z\x17infinite-minesweeper/pbb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_messages_proto_goTypes = []any{
	(*ChunkID)(nil),            // 0: ChunkID
	(*RevealRequest)(nil),      // 1: RevealRequest
	(*SubscribeRequest)(nil),   // 2: SubscribeRequest
	(*UnsubscribeRequest)(nil), // 3: UnsubscribeRequest
	(*SeedRequest)(nil),        // 4: SeedRequest
	(*SeedResponse)(nil),       // 5: SeedResponse
	(*Reveal)(nil),             // 6: Reveal
	(*ChunkSync)(nil),          // 7: ChunkSync
	(*RevealAck)(nil),          // 8: RevealAck
	(*LeaderboardEntry)(nil),   // 9: LeaderboardEntry
	(*Leaderboard)(nil),        // 10: Leaderboard
	(*ClientMessage)(nil),      // 11: ClientMessage
	(*ServerMessage)(nil),      // 12: ServerMessage
}
var file_messages_proto_depIdxs = []int32{
	0,  // 0: RevealRequest.chunk_id:type_name -> ChunkID
	0,  // 1: SubscribeRequest.chunk_id:type_name -> ChunkID
	0,  // 2: UnsubscribeRequest.chunk_id:type_name -> ChunkID
	0,  // 3: SeedRequest.chunk_id:type_name -> ChunkID
	0,  // 4: SeedResponse.chunk_id:type_name -> ChunkID
	0,  // 5: Reveal.chunk_id:type_name -> ChunkID
	0,  // 6: ChunkSync.chunk_id:type_name -> ChunkID
	6,  // 7: ChunkSync.reveals:type_name -> Reveal
	0,  // 8: RevealAck.chunk_id:type_name -> ChunkID
	9,  // 9: Leaderboard.entries:type_name -> LeaderboardEntry
	1,  // 10: ClientMessage.reveal:type_name -> RevealRequest
	2,  // 11: ClientMessage.subscribe:type_name -> SubscribeRequest
	3,  // 12: ClientMessage.unsubscribe:type_name -> UnsubscribeRequest
	4,  // 13: ClientMessage.seed:type_name -> SeedRequest
	6,  // 14: ServerMessage.reveal:type_name -> Reveal
	8,  // 15: ServerMessage.reveal_ack:type_name -> RevealAck
	5,  // 16: ServerMessage.seed:type_name -> SeedResponse
	7,  // 17: ServerMessage.chunk_sync:type_name -> ChunkSync
	10, // 18: ServerMessage.leaderboard:type_name -> Leaderboard
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[11].OneofWrappers = []any{
		(*ClientMessage_Reveal)(nil),
		(*ClientMessage_Subscribe)(nil),
		(*ClientMessage_Unsubscribe)(nil),
		(*ClientMessage_Seed)(nil),
	}
	file_messages_proto_msgTypes[12].OneofWrappers = []any{
		(*ServerMessage_Reveal)(nil),
		(*ServerMessage_RevealAck)(nil),
		(*ServerMessage_Seed)(nil),
		(*ServerMessage_ChunkSync)(nil),
		(*ServerMessage_Leaderboard)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
